### ISSUE TITLE
images in blog roll don't re-size automatically 

### ISSUE THREAD

**Issue by FranziFehr** [VolunteerDublinCity/Dublin-City-Website#33]
# Bug
The images in the blog roll/ overview of blog posts (news and volunteers) don't re-size automatically, so they are all in different formats.  

## Current result and How to recreate
What's wrong?
http://volunteerdublincity.ie/newsblog/news/
http://volunteerdublincity.ie/newsblog/volunteering/

## Expected Result
What should happen normally. 
Wordpress should automatically re-size the images to a consistent size 

## Picture
Attach a screenshot of the bug in action.
![news section image size issue](https://user-images.githubusercontent.com/36622166/39176124-e9ccec6e-47a3-11e8-927f-f4b23c4e8665.png)

## Environment 
- Operating System: Windows 7 Professional, Version	6.1.7601 Service Pack 1 Build 7601

- Browser & Version number (Safari 11.0.0, IE 11): Google Chrome 

## URL
The address of where the bug is happening.

http://volunteerdublincity.ie/newsblog/news/
http://volunteerdublincity.ie/newsblog/volunteering/

# Feature Request
## Description of Feature
In as much detail as you can.

## Goal of feature / What do the users get?
Why this feature is important.

## Picture
Is relevant, attach a napkin doodle or wireframe.

**Comment by Duncan-Mckenna** [comment]
Thanks Franzi. I'll try and get a fix in for that today.

**Comment by Duncan-Mckenna** [comment]
Hi Franzi, could you login and take a look at the blog posts? They should be fixed now. I've also added the calendar for the opportunities that you can see [here](http://volunteerdublincity.ie/vol/dublin-opp/opportunities/?d=null). @JamesAppletonDCVC, can you take a look at that too. 

If that's all good, I'll push that live later today.

**Comment by FranziFehr** [comment]
Hi Duncan,

Apologies for the delayed reply, I have been in appointments for most of the day and James is out sick today.
I had a look at the blog post, and while the image sizing looks much better, the images still seem to have a slightly different size, which looks a bit odd when right beside each other. Also, is there a way to code it that it always pulls in two lines of caption text (even if the second line is empty), so that all the captions and images are at the same level, does that make sense?

I’d like to check with James on the calendar tomorrow and will get back to you. Can I just ask, what date is the entry based on? The activation/ deactivation date or a date that we add manually?

Many thanks, Franzi

**Comment by FranziFehr** [comment]
Hi Duncan, 
I don't think the issue is fixed just yet. I asked a colleague to add a featured image to a blog post yesterday because I was out of the office, and she stuck a full size image. It did not get cropped automatically. I am going to change this manually now, but could you have another look, please? Thank you. 

![image](https://user-images.githubusercontent.com/36622166/40108222-3a9ba4e6-58f2-11e8-8545-5c5cc6ef3515.png)

**Comment by Duncan-Mckenna** [comment]
Hi Franzi, 
Thanks for the screenshot. I'll try and get a look at this as soon as possible today. Unfortunately for the moment, the best thing to do would be to resize the image. This can be done inside the Wordpress, when you click through to the details of the featured image in the post. 

Thanks, 
Duncan

**Comment by FranziFehr** [comment]
Hi Duncan,

No worries, I have reseized the pic manually for now. Because I don’t have clear dimensions needed, they are still all slightly different sizes. I just wanted to let you know it’s still an issue, thanks for looking into it.

Best, Franzi
